name: Compress Images

on:
  workflow_dispatch:
  push:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
      - '**.avif'

jobs:
  compress:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick

      - name: Resize images
        run: find cards -type f \( -name '*.jpg' -o -name '*.jpeg' -o -name '*.png' -o -name '*.webp' \) | xargs mogrify -resize '400x>'

      - uses: calibreapp/image-actions@main
        with:
          compressOnly: true

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: compress images"
