name: Compress Images

on:
  workflow_dispatch:
  push:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
      - '**.avif'

jobs:
  compress:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: calibreapp/image-actions@main
        with:
          compressOnly: true

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: compress images"
